version: '3'

services:
  reveal.js:
    container_name: reveal.js
    build: .
    ports:
      - 9000:8000
    volumes:
      - ./slides:/reveal.js/md
      - ./index.html:/reveal.js/index.html
    command: npm start